# Generated by Django 4.1.5 on 2023-02-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('roll', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
